### ISSUE TITLE
How can we apply ADAPT to another deep neural network model?

### ISSUE THREAD

**Issue by sooyoungcha** [kupl/adapt#1]
We want to apply ADAPT to other deep neural network models, not models used in the paper.
How can we do it?

**Comment by sooyoungcha** [comment]
Maybe we should modify the file "network.py", in the folder "adapt/adapt/network".

**Comment by henrylee97** [comment]
We now supports FCN and CNN based models.
If you want to use FCN and CNN based models just wrap the model with `adapt.Network` class.
If you want to use other models you should modify the `Network` class in the file `adapt/network/network.py`.
