### ISSUE TITLE
Question about experimental results on cifar10 with resnet18(test_acc:86.14%)

### ISSUE THREAD

**Issue by zzydzh** [kupl/adapt#14]
I pick an image for each category in CIFAR10 that predicts correctly, and **metric = TKNC(30)**, for each image, the generation time is **15 seconds**.  I compare adapt and DeepXplore  similarly with your tutorial, but I get poor result in adapt and good result in DeepXplore, It is normal?
Here is the result :

|   method   | total_input(10 image) | total_adversarial(10 image) | Labels |
| :--------: | :-------------------: | :-------------------------: | :----: |
|   adapt    |         2047          |             654             |   20   |
| DeepXplore |         2618          |            2394             |   87   |

**Comment by henrylee97** [comment]
First of all, thank you for your interest in our work.

Adapt's use of online learning to refine the selection strategy may result in a longer time to discover optimal strategies compared to DeepXplore's utilization of a basic, human-designed selection strategy.

As I lost the experimental data during that period, I am unable to provide the expected result from the data outlined in the paper.

**Comment by zzydzh** [comment]
> 

thanks for your reply, I will try more time settings.
