### ISSUE TITLE
Is ADAPT applicable to the other coverage metrics?

### ISSUE THREAD

**Issue by audxo14** [kupl/adapt#7]
If I understand ADAPT correctly, it seems that it only considers two types of neuron coverage as targets to increase.

As a position interested in deep neural networks, what I am wondering is whether ADAPT is also applicable for the other coverage metrics like surprise coverage which was first introduced in ICSE `19 (Guiding deep learning system testing using surprise adequacy).

**Comment by sooyoungcha** [comment]
Yes, ADAPT is applicable for the other coverage metrics. 

To do so, you should separately implement the new coverage metric in the folder "/adapt/metric/".
