### ISSUE TITLE
Questions about the hyper-parameters used in the paper.

### ISSUE THREAD

**Issue by audxo14** [kupl/adapt#8]
There are a lot of hyper-parameters used in the paper, like the number of selected neuron.

Is the effectiveness of ADAPT heavily influenced by the values of hyper-parameters?

**Comment by sooyoungcha** [comment]
Based on our observation, the hyper-parameter values heavily affected the effectiveness of ADAPT. 

As we mentioned in the paper, we manually tuned these hyper-parameters and left automatic tuning as future work.
