### ISSUE TITLE
The performance of ADAPT when considering the different L2-distance between the initial input and mutants.

### ISSUE THREAD

**Issue by audxo14** [kupl/adapt#9]
In the paper, you fixed the L2-distance between the initial input and the mutants as 0.05 on average.

Is the performance of ADAPT dependent to the value of the L2-distance?

If so, what happens to the performance if I change the distance to a smaller value like 0.01??

**Comment by sooyoungcha** [comment]
We did not experimentally evaluate the performance of ADAPT when the distance is 0.01.

Based on our experience, we expect that the performance will deteriorate for a dataset, MNIST, when the distance is 0.01.
